name: Unit tests and project documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    name: "Run tests and generate project documentation"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: [ '3.11' ]
        # TODO: add rust-version 1.62
        # exclude:
        #   - os: macos-latest
        #     python-version: '3.8'
        #   - os: windows-latest
        #     python-version: '3.6'

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        #architecture: x64
    - name: Display Python version
      run: |
        python -c "import sys; print(sys.version)"
    # Install packages (for API doc gen)
    - name: Install library (Python)
      working-directory: .
      run: |
        pip install ".[all]"
    # docs (API)
    # generate python docs using pdoc
    # - name: "Create documentation for Python components (API docs)"
    #   run: |
    #     pdoc --html -c latex_math=True --force --output-dir docs/api/python ailt.db
  
    # test & code coverage (Python)
    # - name: "Unit tests and code coverage reports for Python components"
    #   run: |
    #     pytest -vvv

    # docs (other)
    - name: "Create documentation (other)"
      run: |
        mkdocs build -c
    - name: Deploy docs
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        # see https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        #destination_dir: "docs"
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: ${{ github.event.head_commit.message }}

# name: github pages

# on:
#   push:
#     branches:
#       - main
# 
#   pull_request:
#     branches:
#       - main

# see https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-gatsby
# jobs:
#   build:
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: "16"

      # deps
#       - run: sudo yarn global add gatsby-cli@^4.24.0 --prefix /usr/local
#       - run: yarn add gatsby@^4.24.0
      #- run: gatsby telemetry --disable

      # install deps
 #      - run: yarn install

  #     - name: Cache dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-

      #- run: npm ci
      #- run: yarn run format
      #- run: yarn run test
  #     - run: yarn run clean
  #     - run: PREFIX_PATHS=false yarn run build
  #     - run: mv public ailt && mkdir public && mv ailt public/
  #     - name: Deploy
  #       if: github.ref == 'refs/heads/main'
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
          # see https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./public
  #         #cname: ailt.arizona.edu
  #         user_name: 'github-actions[bot]'
  #         user_email: 'github-actions[bot]@users.noreply.github.com'
  #         commit_message: ${{ github.event.head_commit.message }}
